import { Product } from '../types';
export const PRODUCTS: Product[] = [
  // أقلام ليكويد بول ROTO
  {
    id: 'roto-liquid-ball-blue',
    name: 'قلم ليكويد بول ROTO - أزرق',
    nameEn: 'ROTO Liquid Ball Pen - Blue',
    price: 15,
    image: '/lovable-uploads/486a8fc0-4533-4990-9005-3e5349a24fd3.png',
    description: 'قلم ليكويد بول من ROTO باللون الأزرق، حبر سائل ناعم وجودة عالية',
    category: 'pens',
    subcategory: 'ballpoint',
    brand: 'roto',
    inStock: true,
    featured: true,
    isNew: true,
    salesCount: 25,
    rating: 4.5,
    tags: ['قلم', 'ليكويد', 'أزرق', 'ROTO']
  },
  {
    id: 'roto-liquid-ball-red',
    name: 'قلم ليكويد بول ROTO - أحمر',
    nameEn: 'ROTO Liquid Ball Pen - Red',
    price: 15,
    image: '/lovable-uploads/ebc5cf38-8a31-4d15-8e5f-a302ee359d18.png',
    description: 'قلم ليكويد بول من ROTO باللون الأحمر، حبر سائل ناعم وجودة عالية',
    category: 'pens',
    subcategory: 'ballpoint',
    brand: 'roto',
    inStock: true,
    featured: true,
    isNew: true,
    salesCount: 20,
    rating: 4.5,
    tags: ['قلم', 'ليكويد', 'أحمر', 'ROTO']
  },
  {
    id: 'roto-liquid-ball-black',
    name: 'قلم ليكويد بول ROTO - أسود',
    nameEn: 'ROTO Liquid Ball Pen - Black',
    price: 15,
    image: '/lovable-uploads/fa267649-6d6c-4d95-b9da-e48a51d31f59.png',
    description: 'قلم ليكويد بول من ROTO باللون الأسود، حبر سائل ناعم وجودة عالية',
    category: 'pens',
    subcategory: 'ballpoint',
    brand: 'roto',
    inStock: true,
    featured: true,
    isNew: true,
    salesCount: 30,
    rating: 4.5,
    tags: ['قلم', 'ليكويد', 'أسود', 'ROTO']
  },
  // كشاكيل السلك
  {
    id: 'spiral-notebook-a5-60',
    name: 'كشكول سلك الاستاذ 60ق A5',
    nameEn: 'Professor Spiral Notebook A5 60 Pages',
    price: 30,
    image: '/lovable-uploads/ccf7b48a-dc1f-4ccb-8db2-7a7afa017686.png',
    description: 'كشكول سلك بحجم A5 يحتوي على 60 صفحة، مثالي للطلاب والمدرسين',
    category: 'notebooks',
    subcategory: 'spiral',
    brand: 'الاستاذ',
    inStock: true,
    featured: true,
    isNew: true,
    salesCount: 15,
    rating: 4.7,
    tags: ['كشكول', 'سلك', 'A5', '60ق', 'الاستاذ']
  },
  {
    id: 'spiral-notebook-a5-mohamed-amira',
    name: 'كشكول سلك A5 60 ورقه محمد واميره',
    nameEn: 'Mohamed & Amira Spiral Notebook A5 60 Pages',
    price: 23,
    image: '/lovable-uploads/2c6e6f9e-d9df-436a-b335-5f154a3cbc71.png',
    description: 'كشكول سلك A5 بتصميم محمد وأميرة، 60 ورقة، مثالي للأطفال والطلاب',
    category: 'notebooks',
    subcategory: 'spiral',
    brand: 'محمد واميره',
    inStock: true,
    featured: true,
    isNew: true,
    salesCount: 8,
    rating: 4.6,
    tags: ['كشكول', 'سلك', 'A5', '60ق', 'محمد', 'اميره', 'أطفال']
  },
  {
    id: 'spiral-notebook-a5-mohamed-amira-80',
    name: 'كشكول سلك محمد واميره 80 ق A5 فسفوري ملون',
    nameEn: 'Mohamed & Amira Spiral Notebook A5 80 Pages Fluorescent Colored',
    price: 28,
    image: '/lovable-uploads/d0eda63b-6c05-4fd9-9f46-17e673d90af2.png',
    description: 'كشكول سلك A5 بتصميم محمد وأميرة، 80 ورقة، ألوان فسفورية جذابة',
    category: 'notebooks',
    subcategory: 'spiral',
    brand: 'محمد واميره',
    inStock: true,
    featured: true,
    isNew: true,
    salesCount: 12,
    rating: 4.7,
    tags: ['كشكول', 'سلك', 'A5', '80ق', 'محمد', 'اميره', 'فسفوري', 'ملون']
  },
  {
    id: 'spiral-notebook-a5-mohamed-amira-100',
    name: 'كشكول سلك A5 100 ورقه محمد واميره الوان',
    nameEn: 'Mohamed & Amira Spiral Notebook A5 100 Pages Colors',
    price: 33,
    image: '/lovable-uploads/504b4af6-f0fc-4983-8c85-9268a6a0d96c.png',
    description: 'كشكول سلك A5 بتصميم محمد وأميرة، 100 ورقة ملونة، جودة عالية',
    category: 'notebooks',
    subcategory: 'spiral',
    brand: 'محمد واميره',
    inStock: true,
    featured: true,
    isNew: true,
    salesCount: 18,
    rating: 4.8,
    tags: ['كشكول', 'سلك', 'A5', '100ق', 'محمد', 'اميره', 'الوان']
  }
];
